
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from 'next/dynamic';
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import NavBar from "@/components/NavBar";
import { useEffect, useState } from "react";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RescueRush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
     

      
    </html>
    </ClerkProvider>
  );
}
